### ISSUE TITLE
RuntimeError Discussion

### ISSUE THREAD

**Issue by NUS-Tim** [FengheTan9/Medical-Image-Segmentation-Benchmarks#7]
I'm encountering a RuntimeError regarding the "SwinUnet" as below.

```
Traceback (most recent call last):
  File "C:\Users\e0575844\Desktop\SBM V2\train.py", line 195, in <module>
    main(args)
  File "C:\Users\e0575844\Desktop\SBM V2\train.py", line 144, in main
    loss = criterion(outputs, label_batch)
  File "C:\Users\e0575844\Anaconda3\envs\MedAugment\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\e0575844\Desktop\SBM V2\src\utils\losses.py", line 18, in forward
    input = input.view(num, -1)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

As replacing the view can affect the remaining approaches, I'm searching for any solution to handle the model itself rather than the loss pipeline. Thx.

**Comment by FengheTan9** [comment]
you can refer [this issues](https://github.com/cezannec/capsule_net_pytorch/issues/4)

**Comment by studyfight** [comment]
> I'm encountering a RuntimeError regarding the "SwinUnet" as below.
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\e0575844\Desktop\SBM V2\train.py", line 195, in <module>
>     main(args)
>   File "C:\Users\e0575844\Desktop\SBM V2\train.py", line 144, in main
>     loss = criterion(outputs, label_batch)
>   File "C:\Users\e0575844\Anaconda3\envs\MedAugment\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\e0575844\Desktop\SBM V2\src\utils\losses.py", line 18, in forward
>     input = input.view(num, -1)
> RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
> ```
> 
> As replacing the view can affect the remaining approaches, I'm searching for any solution to handle the model itself rather than the loss pipeline. Thx.

您好，您在运行这个swinUnet的时候面对这行代码您不会报错吗
else:
        # Adjust accordingly for transformer-based models
        model = get_transformer_based_model(model_name=args.model, img_size=args.img_size, num_classes=args.num_classes, in_ch=3)
这里调用get_transformer_based_model的时候没有传parser这个参数，但是这个函数需要传入一个parser参数
def get_transformer_based_model(parser, model_name: str, img_size: int, num_classes: int, in_ch: int):
    if model_name == "MedT":
        model = MedT(img_size=img_size, imgchan=in_ch, num_classes=num_classes)
    elif model_name == "SwinUnet":
        parser.add_argument('--zip', action='store_true',
                            help='use zipped dataset instead of folder dataset')
        parser.add_argument(
            '--cfg', type=str, default="./src/network/transfomer_based/swinUnet/swin_tiny_patch4_window7_224_lite.yaml",
            help='path to config file', )
        parser.add_argument(
            "--opts",
            help="Modify config options by adding 'KEY VALUE' pairs. ",
            default=None,
            nargs='+',
        )
        parser.add_argument('--cache-mode', type=str, default='part', choices=['no', 'full', 'part'],
                            help='no: no cache, '
                                 'full: cache all data, '
                                 'part: sharding the dataset into nonoverlapping pieces and only cache one piece')
        parser.add_argument('--resume', help='resume from checkpoint')
        parser.add_argument('--accumulation-steps', type=int,
                            help="gradient accumulation steps")
        parser.add_argument('--use-checkpoint', action='store_true',
                            help="whether to use gradient checkpointing to save memory")
        parser.add_argument('--amp-opt-level', type=str, default='O1', choices=['O0', 'O1', 'O2'],
                            help='mixed precision opt level, if O0, no amp is used')
        parser.add_argument('--tag', help='tag of experiment')
        parser.add_argument('--eval', action='store_true',
                            help='Perform evaluation only')
        parser.add_argument('--throughput', action='store_true',
                            help='Test throughput only')
        config = get_config(parser.parse_args())
        model = SwinUnet(config, img_size=224, num_classes=num_classes)
    elif model_name == "TransUnet":
        model = TransUnet(img_ch=in_ch, output_ch=num_classes)
    else:
        model = None
        print("model err")
        exit(0)
    return model
